<?php

namespace app\modules\apiTesting\widgets;

use app\modules\apiTesting\models\ApiTestProject;
use app\modules\apiTesting\models\ApiTestServer;
use SebastianBergmann\CodeCoverage\Report\Xml\Project;
use yii\base\Exception;
use yii\base\Widget;

/**
 * Class ServerDropdownMenu
 *
 * @package app\modules\apiTesting\widgets
 * @var $project ApiTestProject
 */
class ProjectDropdownMenu extends Widget
{
    public $project;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ( ! $this->project) {
            throw new Exception('Please set an server model for use this widget');
        }
    }

    public function run()
    {
        parent::run();
        return $this->render('server-dropdown-menu', [
            'project' => $this->project
        ]);
    }
}
