# https://codeclimate.com
version: "2"
checks:
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-lines:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false
# https://docs.codeclimate.com/docs/list-of-engines
plugins:
  csslint:
    enabled: true
  duplication:
    enabled: false
    config:
      count_threshold: 3
      languages:
      - javascript
      - php
  editorconfig:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      config: .eslintrc
  fixme:
    enabled: true
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
  phan:
    enabled: true
    config:
      file_extensions: "php"
      ignore-undeclared: true
    checks:
      PhanUndeclaredClassMethod:
        enabled: false
      PhanUndeclaredProperty:
        enabled: false
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR1,PSR2,Yii2"
      encoding: utf-8
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "unusedcode,codesize,naming,phpmd.xml"
  sonar-php:
    enabled: true
    config:
      minimum_severity: critical
  stylelint:
    enabled: true
exclude_patterns:
  - "/vendor/"
