# https://codeclimate.com
version: "2"
checks:
  argument-count:
    enabled: false
  file-lines:
    enabled: false
  method-count:
    enabled: false
  method-complexity:
    enabled: false
  method-lines:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false
# https://docs.codeclimate.com/docs/list-of-engines
plugins:
  csslint:
    enabled: true
  duplication:
    enabled: false
    config:
      count_threshold: 3
      languages:
      - javascript
      - php
  editorconfig:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      config: .eslintrc
  fixme:
    enabled: true
    checks:
      TODO:
        enabled: false
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
  phan:
    enabled: true
    config:
      file_extensions: "php"
      ignore-undeclared: true
    checks:
      PhanUndeclaredClassMethod:
        enabled: false
      PhanUndeclaredProperty:
        enabled: false
      PhanUnreferencedUseNormal:
        enabled: false
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      encoding: utf-8
      standard: "PSR1,PSR2,Yii2,phpcs.xml" # add PSR12 when codeclimate installs it
    checks:
      Yii2 Properties PrivatePropertiesUnderscore NoUnderscore:
        enabled: false
      Generic Files LineLength TooLong:
        enabled: false
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "unusedcode,codesize,naming,phpmd.xml"
    # https://phpmd.org/rules/
    checks:
      CleanCode/ElseExpression:
        enabled: false
      CyclomaticComplexity:
        enabled: false
      Design/CouplingBetweenObjects:
        enabled: false
      Design/LongClass:
        enabled: false
      Design/LongMethod:
        enabled: false
      Design/LongParameterList:
        enabled: false
      Design/NpathComplexity:
        enabled: false
      Design/TooManyFields:
        enabled: false
      Design/TooManyMethods:
        enabled: false
      Design/TooManyPublicMethods:
        enabled: false
      Design/WeightedMethodCount:
        enabled: false
      Naming/LongVariable:
        enabled: false
      Naming/ShortVariable:
        enabled: false
  sonar-php:
    enabled: true
    config:
      file_extensions: "php"
      minimum_severity: critical
    checks:
      php:S1192:
        enabled: false
      php:S3776:
        enabled: false
  stylelint:
    enabled: true
exclude_patterns:
  - "/vendor/"
