# https://scrutinizer-ci.com/g/opensourcewebsite-org/opensourcewebsite-org
# https://scrutinizer-ci.com/docs/
# For more PHP information and examples, see https://scrutinizer-ci.com/docs/guides/php
build:
  environment:
    php: 7.4
  nodes:
    mysql:
      services:
        # For available tags, see https://hub.docker.com/_/mysql/
        mysql:
          image: mysql/mysql-server:8.0
          command: --default-authentication-plugin=mysql_native_password
  dependencies:
    before:
      - cp .env.test.dist .env.test
      - cp config/params.dist.php config/params.php
      - cp config/web-local.dist.php config/web-local.php
      - export PATH="$HOME/.composer/vendor/bin:$PATH"
      - composer install --prefer-dist --no-interaction
      - php --version
      - php -m
      #- mysql --version
      - mysql -uroot -e 'SHOW VARIABLES like "version"';
      - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS opensourcewebsite_test CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;"
      - ./tests/bin/yii migrate --interactive=0 -c
      - ./tests/bin/yii fixture/load '*' --interactive=0
  tests:
    override:
      -
        command: './vendor/bin/codecept run unit --coverage'
      - php-scrutinizer-run
      -
        command: phpcs-run
        use_website_config: false
      - js-scrutinizer-run
      -
        command: jshint-run
        use_website_config: false
tools:
  external_code_coverage: false
  php_mess_detector: true
  php_code_sniffer: true
  sensiolabs_security_checker: true
  php_code_coverage: true
  php_pdepend: true
  php_loc:
    enabled: true
    excluded_dirs: [vendor, test]
  php_cpd:
    enabled: true
    excluded_dirs: [vendor, test]
filter:
  excluded_paths:
    - 'tests/*'
    - 'vendor/*'
checks:
  php:
    duplication: false
    unused_methods: false
    unused_parameters: false
    argument_type_checks: false
    verify_property_names: false
    method_calls_on_non_object: false
    fix_doc_comments: false
    instanceof_class_exists: false
    catch_class_exists: false
    assignment_of_null_return: false
    use_statement_alias_conflict: false
  javascript: true
coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true
