<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Privacy Policy' => 'Политика конфиденциальности',
    'Terms of Use' => 'Условия обслуживания',
    'What the site will look like and what functions it will have depends only on the users\' decisions.' => '',
    'online community' => 'онлайн сообщество',
    'online community managed by users using electronic voting and modifying source code' => 'онлайн сообщество которым управляют пользователи используя электронные голосования и изменяя исходный код',
    'Account' => 'Аккаунт',
    'Tell Me More' => 'Узнать больше',
    'How It Works' => 'Как это работает',
    'Our Mission & Vision' => 'Наша миссия и видение',
    'Our Principles & Values' => 'Наши принципы и ценности',
    'Features & Plans' => 'Возможности и планы',
    'Membership & Loyalty Program' => 'Членство и программа лояльности',
    'Donation & Crowdfunding' => 'Пожертвования и краудфандинг',
    'Contribution' => 'Участие в разработке и помощь проекту',
    'Technologies We Use' => 'Используемые технологии',
    'Web Services We Use' => 'Используемые сервисы',
    'Join Us' => 'Присоединяйтесь к нам',
    'Join us and be part of the digital future' => 'Присоединяйтесь к нам и станьте частью цифрового будущего',
    'Join us and let’s build the future together' => 'Присоединяйтесь к нам и давайте создавать это будущее вместе',
    'Debt Redistribution' => 'Перераспределение долгов',
    'Debt Redistribution for user "#{userId}"' => 'Перераспределение долгов для Пользователя "#{userId}"',
    'Loyalty program' => 'Программа лояльности',
    'Logout' => 'Выход',
    'Profile' => 'Профиль',
    'Name' => 'Название',
    'Save' => 'Сохранить',
    'Cancel' => 'Отменить',
    'Rating provides' => 'Рейтинг дает',
    'Edit' => 'Изменить',
    'Soon the loyalty program will be significantly increased and new bonuses will be added' => 'В ближайшее время программа лояльности будет значительно расширена и будут добавлены новые бонусы',
    'Your donations increase your Rating in our community' => 'Ваши пожертвования повышают ваш рейтинг в нашем сообществе',
    'Your contributions increase your Rating in our community' => 'Ваша помощь проекту повышает ваш рейтинг в нашем сообществе',
    'We accepts volunteers and interns who demonstrate appropriate skills and express a strong interest in one or more of the following areas' => 'Мы принимаем добровольцев и стажеров, которые демонстрируют соответствующие навыки и проявляют большой интерес к одной или нескольким из следующих областей',
    'open source development, open data, editorial and translation work, UI/UX web design, social media and communications' => ' разработка с открытым исходным кодом, открытые данные, редакционная и переводческая работа, UI/UX веб-дизайн, социальные медиа и коммуникации',
    'Delete' => 'Удалить',
    'Your browser doesn`t support cookies' => 'Ваш браузер не поддерживает куки',
    'Please, enable it in browser preferences for using all capabilities of Open Source Website' => 'Пожалуйста, включите их в настройках браузера для использования всех возможностей Open Source Website',
    'Contacts' => 'Контакты',
    'Create Contact' => 'Добавление контакта',
    'User ID / Username (optional)' => 'ID пользователя / Имя пользователя (необязательно)',
    'Name (optional)' => 'Имя (необязательно)',
    'Is Real' => 'Реальный',
    'Real' => 'Реальный',
    'Relation' => 'Отношение',
    'Neutral' => 'Нейтрал',
    'Friend' => 'Друг',
    'Enemy' => 'Враг',
    'Vote Delegation Priority' => 'Приоритет делегирования голоса',
    'Debt Redistribution Priority' => 'Приоритет перераспределения долга',
    'optional' => 'опционально',
    'No priority' => 'Без приоритета',
    'Yes' => 'Да',
    'No' => 'Нет',
    'Source Code' => 'Исходный код',
    'Source code' => 'Исходный код',
    'Attention' => 'Внимание',
    'This feature works in test mode' => 'Этот функционал работает в тестовом режиме',
    'Please help to test all functions of this' => 'Пожалуйста помогите протестировать все функции',
    'All data of debts will be deleted after starting this feature in operating mode' => 'Все данные о долгах будут удалены после запуска этого функционала в рабочий режим',
    'Partners' => 'Партнеры',
    'New matches' => 'Новые совпадения',
];
