<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Privacy Policy' => 'Политика конфиденциальности',
    'Terms of Use' => 'Условия обслуживания',
    'What the site will look like and what functions it will have depends only on the users\' decisions.' => '',
    'online community' => 'онлайн сообщество',
    'Account' => 'Аккаунт',
    'Tell Me More' => 'Узнать больше',
    'How It Works' => 'Как это работает',
    'Our Mission & Vision' => 'Наша миссия и видение',
    'Our Principles & Values' => 'Наши принципы и ценности',
    'Features & Plans' => 'Возможности и планы',
    'Membership & Loyalty Program' => 'Членство и программа лояльности',
    'Donate & Crowdfunding' => 'Пожертвования и краудфандинг',
    'Contribution' => 'Участие в разработке и помощь проекту',
    'Technologies We Use' => 'Используемые технологии',
    'Web Services We Use' => 'Используемые сервисы',
    'Join Us' => 'Присоединяйтесь к нам',
    'Join us and be part of the digital future' => 'Присоединяйтесь к нам и станьте частью цифрового будущего',
    'Beginner' => 'Начальный',
    'Elementary' => 'Элементарный',
    'Intermediate' => 'Средний',
    'Upper-Intermediate' => 'Средне-продвинутый',
    'Advanced' => 'Продвинутый',
    'Proficient' => 'Профессиональный',
    'Native' => 'Родной',
    'Debt Redistribution' => 'Перераспределение долгов',
    'Debt Redistribution for user "#{userId}"' => 'Перераспределение долгов для Пользователя "#{userId}"',
];
