<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Privacy Policy' => 'Политика конфиденциальности',
    'Terms of Use' => 'Условия обслуживания',
    'What the site will look like and what functions it will have depends only on the users\' decisions.' => '',
    'online community' => 'онлайн сообщество',
    'online community managed by users using electronic voting and modifying source code' => 'онлайн сообщество которым управляют пользователи используя электронные голосования и изменяя исходный код',
    'Account' => 'Аккаунт',
    'Tell Me More' => 'Узнать больше',
    'How It Works' => 'Как это работает',
    'Our Mission & Vision' => 'Наша миссия и видение',
    'Our Principles & Values' => 'Наши принципы и ценности',
    'Features & Plans' => 'Возможности и планы',
    'Membership & Loyalty Program' => 'Членство и программа лояльности',
    'Donate & Crowdfunding' => 'Пожертвования и краудфандинг',
    'Contribution' => 'Участие в разработке и помощь проекту',
    'Technologies We Use' => 'Используемые технологии',
    'Web Services We Use' => 'Используемые сервисы',
    'Join Us' => 'Присоединяйтесь к нам',
    'Join us and be part of the digital future' => 'Присоединяйтесь к нам и станьте частью цифрового будущего',
    'Beginner' => 'Начальный',
    'Elementary' => 'Элементарный',
    'Intermediate' => 'Средний',
    'Upper-Intermediate' => 'Средне-продвинутый',
    'Advanced' => 'Продвинутый',
    'Proficient' => 'Профессиональный',
    'Native' => 'Родной',
    'Debt Redistribution' => 'Перераспределение долгов',
    'Debt Redistribution for user "#{userId}"' => 'Перераспределение долгов для Пользователя "#{userId}"',
    'Loyalty program' => 'Программа лояльности',
    'Logout' => 'Выход',
    'Profile' => 'Профиль',
    'Rank' => 'Ранг',
    'Voting Power' => 'Сила голоса',
    'Rating' => 'Рейтинг',
    'Active Rating' => 'Активный рейтинг',
    'Username' => 'Имя пользователя',
    'Name' => 'Имя',
    'Birthday' => 'День рождения',
    'Gender' => 'Пол',
    'Sexuality' => 'Сексуальная ориентация',
    'Timezone' => 'Часовой пояс',
    'Currency' => 'Валюта',
    'Save' => 'Сохранить',
    'Cancel' => 'Отменить',
    'Edit email' => 'Изменить email',
    'Edit birthday' => 'Изменить день рождения',
    'Edit currency' => 'Изменить валюту',
    'Edit gender' => 'Изменить пол',
    'Edit name' => 'Изменить имя',
    'Edit sexuality' => 'Изменить сексуальную ориентацию',
    'Edit timezone' => 'Изменить часовой пояс',
    'Edit username' => 'Изменить имя пользователя',
    'Edit' => 'Изменить',
    'Male' => 'Мужчина',
    'Female' => 'Женщина',
    'Rating provides' => 'Рейтинг дает',
    'Soon the loyalty program will be significantly increased and new bonuses will be added' => 'В ближайшее время программа лояльности будет значительно расширена и будут добавлены новые бонусы',
    'Your donations increase your Rating in our community' => 'Ваши пожертвования повышает ваш рейтинг в нашем сообществе',
    'Your contributions increase your Rating in our community' => 'Ваша помощь повышает ваш рейтинг в нашем сообществе',
    'We accepts volunteers and interns who demonstrate appropriate skills and express a strong interest in one or more of the following areas' => 'Мы принимаем добровольцев и стажеров, которые демонстрируют соответствующие навыки и проявляют большой интерес к одной или нескольким из следующих областей',
    'open source development, open data, editorial and translation work, UI/UX web design, social media and communications' => ' разработка с открытым исходным кодом, открытые данные, редакционная и переводческая работа, UI/UX веб-дизайн, социальные медиа и коммуникации',
    'Language' => 'Язык',
    'Languages' => 'Языки',
    'Citizenships' => 'Гражданства',
    'Citizenship' => 'Гражданство',
    'Delete' => 'Удалить',
    'Add language' => 'Добавить язык',
    'Change language' => 'Изменить язык',
    'Level' => 'Уровень владения',
    'Add citizenship' => 'Добавить гражданство',
    'Edit language' => 'Изменить язык',
    'Your browser doesn`t support cookies' => 'Ваш браузер не поддерживает куки',
    'Please, enable it in browser preferences for using all capabilities of Open Source Website' => 'Пожалуйста, включите их в настройках браузера для использования всех возможностей Open Source Website',
];
