<?php

use yii\db\Migration;

/**
 * Class m180719_050202_import_countries
 */
class m180719_050202_import_countries extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->execute('SET FOREIGN_KEY_CHECKS=0');
        $this->truncateTable('{{%country}}');

        $this->execute("INSERT INTO `country` (`id`, `name`, `code`, `slug`, `wikipedia`) VALUES
        (1, 'Afghanistan', 'AF', 'afghanistan', 'https://en.wikipedia.org/wiki/Afghanistan'),
        (2, 'Aland Islands', 'AX', 'aland-islands', 'https://en.wikipedia.org/wiki/Åland_Islands'),
        (3, 'Albania', 'AL', 'albania', 'https://en.wikipedia.org/wiki/Albania'),
        (4, 'Algeria', 'DZ', 'algeria', 'https://en.wikipedia.org/wiki/Algeria'),
        (5, 'American Samoa', 'AS', 'american-samoa', 'https://en.wikipedia.org/wiki/American_Samoa'),
        (6, 'Andorra', 'AD', 'andorra', 'https://en.wikipedia.org/wiki/Andorra'),
        (7, 'Angola', 'AO', 'angola', 'https://en.wikipedia.org/wiki/Angola'),
        (8, 'Anguilla', 'AI', 'anguilla', 'https://en.wikipedia.org/wiki/Anguilla'),
        (9, 'Antarctica', 'AQ', 'antarctica', 'https://en.wikipedia.org/wiki/Antarctica'),
        (10, 'Antigua and Barbuda', 'AG', 'antigua-and-barbuda', 'https://en.wikipedia.org/wiki/Antigua_and_Barbuda'),
        (11, 'Argentina', 'AR', 'argentina', 'https://en.wikipedia.org/wiki/Argentina'),
        (12, 'Armenia', 'AM', 'armenia', 'https://en.wikipedia.org/wiki/Armenia'),
        (13, 'Aruba', 'AW', 'aruba', 'https://en.wikipedia.org/wiki/Aruba'),
        (14, 'Australia', 'AU', 'australia', 'https://en.wikipedia.org/wiki/Australia'),
        (15, 'Austria', 'AT', 'austria', 'https://en.wikipedia.org/wiki/Austria'),
        (16, 'Azerbaijan', 'AZ', 'azerbaijan', 'https://en.wikipedia.org/wiki/Azerbaijan'),
        (17, 'Bahamas', 'BS', 'the-bahamas', 'https://en.wikipedia.org/wiki/The_Bahamas'),
        (18, 'Bahrain', 'BH', 'bahrain', 'https://en.wikipedia.org/wiki/Bahrain'),
        (19, 'Bangladesh', 'BD', 'bangladesh', 'https://en.wikipedia.org/wiki/Bangladesh'),
        (20, 'Barbados', 'BB', 'barbados', 'https://en.wikipedia.org/wiki/Barbados'),
        (21, 'Belarus', 'BY', 'belarus', 'https://en.wikipedia.org/wiki/Belarus'),
        (22, 'Belgium', 'BE', 'belgium', 'https://en.wikipedia.org/wiki/Belgium'),
        (23, 'Belize', 'BZ', 'belize', 'https://en.wikipedia.org/wiki/Belize'),
        (24, 'Benin', 'BJ', 'benin', 'https://en.wikipedia.org/wiki/Benin'),
        (25, 'Bermuda', 'BM', 'bermuda', 'https://en.wikipedia.org/wiki/Bermuda'),
        (26, 'Bhutan', 'BT', 'bhutan', 'https://en.wikipedia.org/wiki/Bhutan'),
        (27, 'Bolivia (Plurinational State of)', 'BO', 'bolivia', 'https://en.wikipedia.org/wiki/Bolivia'),
        (28, 'Bonaire, Sint Eustatius and Saba', 'BQ', 'bonaire', 'https://en.wikipedia.org/wiki/Bonaire'),
        (29, 'Bosnia and Herzegovina', 'BA', 'bosnia-and-herzegovina', 'https://en.wikipedia.org/wiki/Bosnia_and_Herzegovina'),
        (30, 'Botswana', 'BW', 'botswana', 'https://en.wikipedia.org/wiki/Botswana'),
        (31, 'Bouvet Island', 'BV', 'bouvet-island', 'https://en.wikipedia.org/wiki/Bouvet_Island'),
        (32, 'Brazil', 'BR', 'brazil', 'https://en.wikipedia.org/wiki/Brazil'),
        (33, 'British Indian Ocean Territory', 'IO', 'british-indian-ocean-territory', 'https://en.wikipedia.org/wiki/British_Indian_Ocean_Territory'),
        (34, 'Brunei Darussalam', 'BN', 'brunei', 'https://en.wikipedia.org/wiki/Brunei'),
        (35, 'Bulgaria', 'BG', 'bulgaria', 'https://en.wikipedia.org/wiki/Bulgaria'),
        (36, 'Burkina Faso', 'BF', 'burkina-faso', 'https://en.wikipedia.org/wiki/Burkina_Faso'),
        (37, 'Burundi', 'BI', 'burundi', 'https://en.wikipedia.org/wiki/Burundi'),
        (38, 'Cambodia', 'KH', 'cambodia', 'https://en.wikipedia.org/wiki/Cambodia'),
        (39, 'Cameroon', 'CM', 'cameroon', 'https://en.wikipedia.org/wiki/Cameroon'),
        (40, 'Canada', 'CA', 'canada', 'https://en.wikipedia.org/wiki/Canada'),
        (41, 'Cabo Verde', 'CV', 'cape-verde', 'https://en.wikipedia.org/wiki/Cape_Verde'),
        (42, 'Cayman Islands', 'KY', 'cayman-islands', 'https://en.wikipedia.org/wiki/Cayman_Islands'),
        (43, 'Central African Republic', 'CF', 'central-african-republic', 'https://en.wikipedia.org/wiki/Central_African_Republic'),
        (44, 'Chad', 'TD', 'chad', 'https://en.wikipedia.org/wiki/Chad'),
        (45, 'Chile', 'CL', 'chile', 'https://en.wikipedia.org/wiki/Chile'),
        (46, 'China', 'CN', 'china', 'https://en.wikipedia.org/wiki/China'),
        (47, 'Christmas Island', 'CX', 'christmas-island', 'https://en.wikipedia.org/wiki/Christmas_Island'),
        (48, 'Cocos (Keeling) Islands', 'CC', 'cocos-keeling-islands', 'https://en.wikipedia.org/wiki/Cocos_(Keeling)_Islands'),
        (49, 'Colombia', 'CO', 'colombia', 'https://en.wikipedia.org/wiki/Colombia'),
        (50, 'Comoros', 'KM', 'comoros', 'https://en.wikipedia.org/wiki/Comoros'),
        (51, 'Congo, Democratic Republic of the', 'CG', 'democratic-republic-of-the-congo', 'https://en.wikipedia.org/wiki/Democratic_Republic_of_the_Congo'),
        (53, 'Cook Islands', 'CK', 'cook-islands', 'https://en.wikipedia.org/wiki/Cook_Islands'),
        (54, 'Costa Rica', 'CR', 'costa-rica', 'https://en.wikipedia.org/wiki/Costa_Rica'),
        (55, 'Côte d\'Ivoire', 'CI', 'ivory-coast', 'https://en.wikipedia.org/wiki/Ivory_Coast'),
        (56, 'Croatia', 'HR', 'croatia', 'https://en.wikipedia.org/wiki/Croatia'),
        (57, 'Cuba', 'CU', 'cuba', 'https://en.wikipedia.org/wiki/Cuba'),
        (58, 'Curaçao', 'CW', 'curaçao', 'https://en.wikipedia.org/wiki/Curaçao'),
        (59, 'Cyprus', 'CY', 'cyprus', 'https://en.wikipedia.org/wiki/Cyprus'),
        (60, 'Czech Republic', 'CZ', 'czech-republic', 'https://en.wikipedia.org/wiki/Czech_Republic'),
        (61, 'Denmark', 'DK', 'denmark', 'https://en.wikipedia.org/wiki/Denmark'),
        (62, 'Djibouti', 'DJ', 'djibouti', 'https://en.wikipedia.org/wiki/Djibouti'),
        (63, 'Dominica', 'DM', 'dominica', 'https://en.wikipedia.org/wiki/Dominica'),
        (64, 'Dominican Republic', 'DO', 'dominican-republic', 'https://en.wikipedia.org/wiki/Dominican_Republic'),
        (65, 'Ecuador', 'EC', 'ecuador', 'https://en.wikipedia.org/wiki/Ecuador'),
        (66, 'Egypt', 'EG', 'egypt', 'https://en.wikipedia.org/wiki/Egypt'),
        (67, 'El Salvador', 'SV', 'el-salvador', 'https://en.wikipedia.org/wiki/El_Salvador'),
        (68, 'Equatorial Guinea', 'GQ', 'equatorial-guinea', 'https://en.wikipedia.org/wiki/Equatorial_Guinea'),
        (69, 'Eritrea', 'ER', 'eritrea', 'https://en.wikipedia.org/wiki/Eritrea'),
        (70, 'Estonia', 'EE', 'estonia', 'https://en.wikipedia.org/wiki/Estonia'),
        (71, 'Ethiopia', 'ET', 'ethiopia', 'https://en.wikipedia.org/wiki/Ethiopia'),
        (72, 'Falkland Islands (Malvinas)', 'FK', 'falkland-islands', 'https://en.wikipedia.org/wiki/Falkland_Islands'),
        (73, 'Faroe Islands', 'FO', 'faroe-islands', 'https://en.wikipedia.org/wiki/Faroe_Islands'),
        (74, 'Fiji', 'FJ', 'fiji', 'https://en.wikipedia.org/wiki/Fiji'),
        (75, 'Finland', 'FI', 'finland', 'https://en.wikipedia.org/wiki/Finland'),
        (76, 'France', 'FR', 'france', 'https://en.wikipedia.org/wiki/France'),
        (77, 'French Guiana', 'GF', 'french-guiana', 'https://en.wikipedia.org/wiki/French_Guiana'),
        (78, 'French Polynesia', 'PF', 'french-polynesia', 'https://en.wikipedia.org/wiki/French_Polynesia'),
        (79, 'French Southern Territories', 'TF', 'french-southern-and-antarctic-lands', 'https://en.wikipedia.org/wiki/French_Southern_and_Antarctic_Lands'),
        (80, 'Gabon', 'GA', 'gabon', 'https://en.wikipedia.org/wiki/Gabon'),
        (81, 'Gambia', 'GM', 'the-gambia', 'https://en.wikipedia.org/wiki/The_Gambia'),
        (82, 'Georgia', 'GE', 'georgia-country', 'https://en.wikipedia.org/wiki/Georgia_(country)'),
        (83, 'Germany', 'DE', 'germany', 'https://en.wikipedia.org/wiki/Germany'),
        (84, 'Ghana', 'GH', 'ghana', 'https://en.wikipedia.org/wiki/Ghana'),
        (85, 'Gibraltar', 'GI', 'gibraltar', 'https://en.wikipedia.org/wiki/Gibraltar'),
        (86, 'Greece', 'GR', 'greece', 'https://en.wikipedia.org/wiki/Greece'),
        (87, 'Greenland', 'GL', 'greenland', 'https://en.wikipedia.org/wiki/Greenland'),
        (88, 'Grenada', 'GD', 'grenada', 'https://en.wikipedia.org/wiki/Grenada'),
        (89, 'Guadeloupe', 'GP', 'guadeloupe', 'https://en.wikipedia.org/wiki/Guadeloupe'),
        (90, 'Guam', 'GU', 'guam', 'https://en.wikipedia.org/wiki/Guam'),
        (91, 'Guatemala', 'GT', 'guatemala', 'https://en.wikipedia.org/wiki/Guatemala'),
        (92, 'Guernsey', 'GG', 'guernsey', 'https://en.wikipedia.org/wiki/Guernsey'),
        (93, 'Guinea', 'GN', 'guinea', 'https://en.wikipedia.org/wiki/Guinea'),
        (94, 'Guinea-Bissau', 'GW', 'guinea-bissau', 'https://en.wikipedia.org/wiki/Guinea-Bissau'),
        (95, 'Guyana', 'GY', 'guyana', 'https://en.wikipedia.org/wiki/Guyana'),
        (96, 'Haiti', 'HT', 'haiti', 'https://en.wikipedia.org/wiki/Haiti'),
        (97, 'Heard Island and McDonald Islands', 'HM', 'heard-island-and-mcdonald-islands', 'https://en.wikipedia.org/wiki/Heard_Island_and_McDonald_Islands'),
        (98, 'Holy See', 'VA', 'holy-see', 'https://en.wikipedia.org/wiki/Holy_See'),
        (99, 'Honduras', 'HN', 'honduras', 'https://en.wikipedia.org/wiki/Honduras'),
        (100, 'Hong Kong', 'HK', 'hong-kong', 'https://en.wikipedia.org/wiki/Hong_Kong'),
        (101, 'Hungary', 'HU', 'hungary', 'https://en.wikipedia.org/wiki/Hungary'),
        (102, 'Iceland', 'IS', 'iceland', 'https://en.wikipedia.org/wiki/Iceland'),
        (103, 'India', 'IN', 'india', 'https://en.wikipedia.org/wiki/India'),
        (104, 'Indonesia', 'ID', 'indonesia', 'https://en.wikipedia.org/wiki/Indonesia'),
        (105, 'Iran (Islamic Republic of)', 'IR', 'iran', 'https://en.wikipedia.org/wiki/Iran'),
        (106, 'Iraq', 'IQ', 'iraq', 'https://en.wikipedia.org/wiki/Iraq'),
        (107, 'Ireland', 'IE', 'ireland', 'https://en.wikipedia.org/wiki/Ireland'),
        (108, 'Isle of Man', 'IM', 'isle-of-man', 'https://en.wikipedia.org/wiki/Isle_of_Man'),
        (109, 'Israel', 'IL', 'israel', 'https://en.wikipedia.org/wiki/Israel'),
        (110, 'Italy', 'IT', 'italy', 'https://en.wikipedia.org/wiki/Italy'),
        (111, 'Jamaica', 'JM', 'jamaica', 'https://en.wikipedia.org/wiki/Jamaica'),
        (112, 'Japan', 'JP', 'japan', 'https://en.wikipedia.org/wiki/Japan'),
        (113, 'Jersey', 'JE', 'jersey', 'https://en.wikipedia.org/wiki/Jersey'),
        (114, 'Jordan', 'JO', 'jordan', 'https://en.wikipedia.org/wiki/Jordan'),
        (115, 'Kazakhstan', 'KZ', 'kazakhstan', 'https://en.wikipedia.org/wiki/Kazakhstan'),
        (116, 'Kenya', 'KE', 'kenya', 'https://en.wikipedia.org/wiki/Kenya'),
        (117, 'Kiribati', 'KI', 'kiribati', 'https://en.wikipedia.org/wiki/Kiribati'),
        (118, 'Korea (Democratic People\'s Republic of)', 'KP', 'north-korea', 'https://en.wikipedia.org/wiki/North_Korea'),
        (119, 'Korea (Republic of)', 'KR', 'south-korea', 'https://en.wikipedia.org/wiki/South_Korea'),
        (120, 'Kuwait', 'KW', 'kuwait', 'https://en.wikipedia.org/wiki/Kuwait'),
        (121, 'Kyrgyzstan', 'KG', 'kyrgyzstan', 'https://en.wikipedia.org/wiki/Kyrgyzstan'),
        (122, 'Lao People\'s Democratic Republic', 'LA', 'laos', 'https://en.wikipedia.org/wiki/Laos'),
        (123, 'Latvia', 'LV', 'latvia', 'https://en.wikipedia.org/wiki/Latvia'),
        (124, 'Lebanon', 'LB', 'lebanon', 'https://en.wikipedia.org/wiki/Lebanon'),
        (125, 'Lesotho', 'LS', 'lesotho', 'https://en.wikipedia.org/wiki/Lesotho'),
        (126, 'Liberia', 'LR', 'liberia', 'https://en.wikipedia.org/wiki/Liberia'),
        (127, 'Libya', 'LY', 'libya', 'https://en.wikipedia.org/wiki/Libya'),
        (128, 'Liechtenstein', 'LI', 'liechtenstein', 'https://en.wikipedia.org/wiki/Liechtenstein'),
        (129, 'Lithuania', 'LT', 'lithuania', 'https://en.wikipedia.org/wiki/Lithuania'),
        (130, 'Luxembourg', 'LU', 'luxembourg', 'https://en.wikipedia.org/wiki/Luxembourg'),
        (131, 'Macau', 'MO', 'macau', 'https://en.wikipedia.org/wiki/Macau'),
        (132, 'Macedonia (the former Yugoslav Republic of)', 'MK', 'republic-of-macedonia', 'https://en.wikipedia.org/wiki/Republic_of_Macedonia'),
        (133, 'Madagascar', 'MG', 'madagascar', 'https://en.wikipedia.org/wiki/Madagascar'),
        (134, 'Malawi', 'MW', 'malawi', 'https://en.wikipedia.org/wiki/Malawi'),
        (135, 'Malaysia', 'MY', 'malaysia', 'https://en.wikipedia.org/wiki/Malaysia'),
        (136, 'Maldives', 'MV', 'maldives', 'https://en.wikipedia.org/wiki/Maldives'),
        (137, 'Mali', 'ML', 'mali', 'https://en.wikipedia.org/wiki/Mali'),
        (138, 'Malta', 'MT', 'malta', 'https://en.wikipedia.org/wiki/Malta'),
        (139, 'Marshall Islands', 'MH', 'marshall-islands', 'https://en.wikipedia.org/wiki/Marshall_Islands'),
        (140, 'Martinique', 'MQ', 'martinique', 'https://en.wikipedia.org/wiki/Martinique'),
        (141, 'Mauritania', 'MR', 'mauritania', 'https://en.wikipedia.org/wiki/Mauritania'),
        (142, 'Mauritius', 'MU', 'mauritius', 'https://en.wikipedia.org/wiki/Mauritius'),
        (143, 'Mayotte', 'YT', 'mayotte', 'https://en.wikipedia.org/wiki/Mayotte'),
        (144, 'Mexico', 'MX', 'mexico', 'https://en.wikipedia.org/wiki/Mexico'),
        (145, 'Micronesia (Federated States of)', 'FM', 'federated-states-of-micronesia', 'https://en.wikipedia.org/wiki/Federated_States_of_Micronesia'),
        (146, 'Moldova (Republic of)', 'MD', 'moldova', 'https://en.wikipedia.org/wiki/Moldova'),
        (147, 'Monaco', 'MC', 'monaco', 'https://en.wikipedia.org/wiki/Monaco'),
        (148, 'Mongolia', 'MN', 'mongolia', 'https://en.wikipedia.org/wiki/Mongolia'),
        (149, 'Montenegro', 'ME', 'montenegro', 'https://en.wikipedia.org/wiki/Montenegro'),
        (150, 'Montserrat', 'MS', 'montserrat', 'https://en.wikipedia.org/wiki/Montserrat'),
        (151, 'Morocco', 'MA', 'morocco', 'https://en.wikipedia.org/wiki/Morocco'),
        (152, 'Mozambique', 'MZ', 'mozambique', 'https://en.wikipedia.org/wiki/Mozambique'),
        (153, 'Myanmar', 'MM', 'myanmar', 'https://en.wikipedia.org/wiki/Myanmar'),
        (154, 'Namibia', 'NA', 'namibia', 'https://en.wikipedia.org/wiki/Namibia'),
        (155, 'Nauru', 'NR', 'nauru', 'https://en.wikipedia.org/wiki/Nauru'),
        (156, 'Nepal', 'NP', 'nepal', 'https://en.wikipedia.org/wiki/Nepal'),
        (157, 'Netherlands', 'NL', 'netherlands', 'https://en.wikipedia.org/wiki/Netherlands'),
        (158, 'New Caledonia', 'NC', 'new-caledonia', 'https://en.wikipedia.org/wiki/New_Caledonia'),
        (159, 'New Zealand', 'NZ', 'new-zealand', 'https://en.wikipedia.org/wiki/New_Zealand'),
        (160, 'Nicaragua', 'NI', 'nicaragua', 'https://en.wikipedia.org/wiki/Nicaragua'),
        (161, 'Niger', 'NE', 'niger', 'https://en.wikipedia.org/wiki/Niger'),
        (162, 'Nigeria', 'NG', 'nigeria', 'https://en.wikipedia.org/wiki/Nigeria'),
        (163, 'Niue', 'NU', 'niue', 'https://en.wikipedia.org/wiki/Niue'),
        (164, 'Norfolk Island', 'NF', 'norfolk-island', 'https://en.wikipedia.org/wiki/Norfolk_Island'),
        (165, 'Northern Mariana Islands', 'MP', 'northern-mariana-islands', 'https://en.wikipedia.org/wiki/Northern_Mariana_Islands'),
        (166, 'Norway', 'NO', 'norway', 'https://en.wikipedia.org/wiki/Norway'),
        (167, 'Oman', 'OM', 'oman', 'https://en.wikipedia.org/wiki/Oman'),
        (168, 'Pakistan', 'PK', 'pakistan', 'https://en.wikipedia.org/wiki/Pakistan'),
        (169, 'Palau', 'PW', 'palau', 'https://en.wikipedia.org/wiki/Palau'),
        (170, 'Palestine, State of', 'PS', 'state-of-palestine', 'https://en.wikipedia.org/wiki/State_of_Palestine'),
        (171, 'Panama', 'PA', 'panama', 'https://en.wikipedia.org/wiki/Panama'),
        (172, 'Papua New Guinea', 'PG', 'papua-new-guinea', 'https://en.wikipedia.org/wiki/Papua_New_Guinea'),
        (173, 'Paraguay', 'PY', 'paraguay', 'https://en.wikipedia.org/wiki/Paraguay'),
        (174, 'Peru', 'PE', 'peru', 'https://en.wikipedia.org/wiki/Peru'),
        (175, 'Philippines', 'PH', 'philippines', 'https://en.wikipedia.org/wiki/Philippines'),
        (176, 'Pitcairn', 'PN', 'pitcairn-islands', 'https://en.wikipedia.org/wiki/Pitcairn_Islands'),
        (177, 'Poland', 'PL', 'poland', 'https://en.wikipedia.org/wiki/Poland'),
        (178, 'Portugal', 'PT', 'portugal', 'https://en.wikipedia.org/wiki/Portugal'),
        (179, 'Puerto Rico', 'PR', 'puerto-rico', 'https://en.wikipedia.org/wiki/Puerto_Rico'),
        (180, 'Qatar', 'QA', 'qatar', 'https://en.wikipedia.org/wiki/Qatar'),
        (181, 'Réunion', 'RE', 'réunion', 'https://en.wikipedia.org/wiki/Réunion'),
        (182, 'Romania', 'RO', 'romania', 'https://en.wikipedia.org/wiki/Romania'),
        (183, 'Russian Federation', 'RU', 'russia', 'https://en.wikipedia.org/wiki/Russia'),
        (184, 'Rwanda', 'RW', 'rwanda', 'https://en.wikipedia.org/wiki/Rwanda'),
        (185, 'Saint Barthélemy', 'BL', 'saint-barthélemy', 'https://en.wikipedia.org/wiki/Saint_Barthélemy'),
        (186, 'Saint Helena, Ascension and Tristan da Cunha', 'SH', 'saint-helena-ascension-and-tristan-da-cunha', 'https://en.wikipedia.org/wiki/Saint_Helena,_Ascension_and_Tristan_da_Cunha'),
        (187, 'Saint Kitts and Nevis', 'KN', 'saint-kitts-and-nevis', 'https://en.wikipedia.org/wiki/Saint_Kitts_and_Nevis'),
        (188, 'Saint Lucia', 'LC', 'saint-lucia', 'https://en.wikipedia.org/wiki/Saint_Lucia'),
        (189, 'Saint Martin (French part)', 'MF', 'saint-martin', 'https://en.wikipedia.org/wiki/Saint_Martin'),
        (190, 'Saint Pierre and Miquelon', 'PM', 'saint-pierre-and-miquelon', 'https://en.wikipedia.org/wiki/Saint_Pierre_and_Miquelon'),
        (191, 'Saint Vincent and the Grenadines', 'VC', 'saint-vincent-and-the-grenadines', 'https://en.wikipedia.org/wiki/Saint_Vincent_and_the_Grenadines'),
        (192, 'Samoa', 'WS', 'samoa', 'https://en.wikipedia.org/wiki/Samoa'),
        (193, 'San Marino', 'SM', 'san-marino', 'https://en.wikipedia.org/wiki/San_Marino'),
        (194, 'Sao Tome and Principe', 'ST', 'são-tomé-and-príncipe', 'https://en.wikipedia.org/wiki/São_Tomé_and_Príncipe'),
        (195, 'Saudi Arabia', 'SA', 'saudi-arabia', 'https://en.wikipedia.org/wiki/Saudi_Arabia'),
        (196, 'Senegal', 'SN', 'senegal', 'https://en.wikipedia.org/wiki/Senegal'),
        (197, 'Serbia', 'RS', 'serbia', 'https://en.wikipedia.org/wiki/Serbia'),
        (198, 'Seychelles', 'SC', 'seychelles', 'https://en.wikipedia.org/wiki/Seychelles'),
        (199, 'Sierra Leone', 'SL', 'sierra-leone', 'https://en.wikipedia.org/wiki/Sierra_Leone'),
        (200, 'Singapore', 'SG', 'singapore', 'https://en.wikipedia.org/wiki/Singapore'),
        (201, 'Sint Maarten (Dutch part)', 'SX', 'sint-maarten', 'https://en.wikipedia.org/wiki/Sint_Maarten'),
        (202, 'Slovakia', 'SK', 'slovakia', 'https://en.wikipedia.org/wiki/Slovakia'),
        (203, 'Slovenia', 'SI', 'slovenia', 'https://en.wikipedia.org/wiki/Slovenia'),
        (204, 'Solomon Islands', 'SB', 'solomon-islands', 'https://en.wikipedia.org/wiki/Solomon_Islands'),
        (205, 'Somalia', 'SO', 'somalia', 'https://en.wikipedia.org/wiki/Somalia'),
        (206, 'South Africa', 'ZA', 'south-africa', 'https://en.wikipedia.org/wiki/South_Africa'),
        (207, 'South Georgia and the South Sandwich Islands', 'GS', 'south-georgia-and-the-south-sandwich-islands', 'https://en.wikipedia.org/wiki/South_Georgia_and_the_South_Sandwich_Islands'),
        (208, 'South Sudan', 'SS', 'south-sudan', 'https://en.wikipedia.org/wiki/South_Sudan'),
        (209, 'Spain', 'ES', 'spain', 'https://en.wikipedia.org/wiki/Spain'),
        (210, 'Sri Lanka', 'LK', 'sri-lanka', 'https://en.wikipedia.org/wiki/Sri_Lanka'),
        (211, 'Sudan', 'SD', 'sudan', 'https://en.wikipedia.org/wiki/Sudan'),
        (212, 'Suriname', 'SR', 'suriname', 'https://en.wikipedia.org/wiki/Suriname'),
        (213, 'Svalbard and Jan Mayen', 'SJ', 'svalbard-and-jan-mayen', 'https://en.wikipedia.org/wiki/Svalbard_and_Jan_Mayen'),
        (214, 'Swaziland', 'SZ', 'swaziland', 'https://en.wikipedia.org/wiki/Swaziland'),
        (215, 'Sweden', 'SE', 'sweden', 'https://en.wikipedia.org/wiki/Sweden'),
        (216, 'Switzerland', 'CH', 'switzerland', 'https://en.wikipedia.org/wiki/Switzerland'),
        (217, 'Syrian Arab Republic', 'SY', 'syria', 'https://en.wikipedia.org/wiki/Syria'),
        (218, 'Taiwan, Province of China', 'TW', 'taiwan-province', 'https://en.wikipedia.org/wiki/Taiwan_Province'),
        (219, 'Tajikistan', 'TJ', 'tajikistan', 'https://en.wikipedia.org/wiki/Tajikistan'),
        (220, 'Tanzania, United Republic of', 'TZ', 'tanzania', 'https://en.wikipedia.org/wiki/Tanzania'),
        (221, 'Thailand', 'TH', 'thailand', 'https://en.wikipedia.org/wiki/Thailand'),
        (222, 'Timor-Leste', 'TL', 'east-timor', 'https://en.wikipedia.org/wiki/East_Timor'),
        (223, 'Togo', 'TG', 'togo', 'https://en.wikipedia.org/wiki/Togo'),
        (224, 'Tokelau', 'TK', 'tokelau', 'https://en.wikipedia.org/wiki/Tokelau'),
        (225, 'Tonga', 'TO', 'tonga', 'https://en.wikipedia.org/wiki/Tonga'),
        (226, 'Trinidad and Tobago', 'TT', 'trinidad-and-tobago', 'https://en.wikipedia.org/wiki/Trinidad_and_Tobago'),
        (227, 'Tunisia', 'TN', 'tunisia', 'https://en.wikipedia.org/wiki/Tunisia'),
        (228, 'Turkey', 'TR', 'turkey', 'https://en.wikipedia.org/wiki/Turkey'),
        (229, 'Turkmenistan', 'TM', 'turkmenistan', 'https://en.wikipedia.org/wiki/Turkmenistan'),
        (230, 'Turks and Caicos Islands', 'TC', 'turks-and-caicos-islands', 'https://en.wikipedia.org/wiki/Turks_and_Caicos_Islands'),
        (231, 'Tuvalu', 'TV', 'tuvalu', 'https://en.wikipedia.org/wiki/Tuvalu'),
        (232, 'Uganda', 'UG', 'uganda', 'https://en.wikipedia.org/wiki/Uganda'),
        (233, 'Ukraine', 'UA', 'ukraine', 'https://en.wikipedia.org/wiki/Ukraine'),
        (234, 'United Arab Emirates', 'AE', 'united-arab-emirates', 'https://en.wikipedia.org/wiki/United_Arab_Emirates'),
        (235, 'United Kingdom of Great Britain and Northern Ireland', 'GB', 'united-kingdom', 'https://en.wikipedia.org/wiki/United_Kingdom'),
        (236, 'United States of America', 'US', 'united-states', 'https://en.wikipedia.org/wiki/United_States'),
        (237, 'United States Minor Outlying Islands', 'UM', 'united-states-minor-outlying-islands', 'https://en.wikipedia.org/wiki/United_States_Minor_Outlying_Islands'),
        (238, 'Uruguay', 'UY', 'uruguay', 'https://en.wikipedia.org/wiki/Uruguay'),
        (239, 'Uzbekistan', 'UZ', 'uzbekistan', 'https://en.wikipedia.org/wiki/Uzbekistan'),
        (240, 'Vanuatu', 'VU', 'vanuatu', 'https://en.wikipedia.org/wiki/Vanuatu'),
        (241, 'Venezuela (Bolivarian Republic of)', 'VE', 'venezuela', 'https://en.wikipedia.org/wiki/Venezuela'),
        (242, 'Vietnam', 'VN', 'vietnam', 'https://en.wikipedia.org/wiki/Vietnam'),
        (243, 'Virgin Islands (British)', 'VG', 'british-virgin-islands', 'https://en.wikipedia.org/wiki/British_Virgin_Islands'),
        (244, 'Virgin Islands (U.S.)', 'VI', 'united-states-virgin-islands', 'https://en.wikipedia.org/wiki/United_States_Virgin_Islands'),
        (245, 'Wallis and Futuna', 'WF', 'wallis-and-futuna', 'https://en.wikipedia.org/wiki/Wallis_and_Futuna'),
        (246, 'Western Sahara', 'EH', 'western-sahara', 'https://en.wikipedia.org/wiki/Western_Sahara'),
        (247, 'Yemen', 'YE', 'yemen', 'https://en.wikipedia.org/wiki/Yemen'),
        (248, 'Zambia', 'ZM', 'zambia', 'https://en.wikipedia.org/wiki/Zambia'),
        (249, 'Zimbabwe', 'ZW', 'zimbabwe', 'https://en.wikipedia.org/wiki/Zimbabwe');
        ");
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        echo "m180719_050202_import_countries cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m180719_050202_import_countries cannot be reverted.\n";

        return false;
    }
    */
}
