<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Code repository ' => '',
    'Donate' => '',
    'Issues' => '',
    'Privacy Policy' => '',
    'Terms of Use' => '',
    'What the site will look like and what functions it will have depends only on the users\' decisions.' => '',
    'Wiki' => '',
    'is an open source website for online social community. The site is managed by users. Any user can suggest changes to the code. The site is updated on the server after each code change. Thus, anyone can influence the functions of the site.' => '',
];
