<?php

namespace app\modules\apiTesting\commands;

use app\modules\apiTesting\services\RunnerService;
use yii\console\Controller;

/**
 * Class RunnerController
 *
 * @package app\modules\apiTesting\commands
 * @property RunnerService $runnerService
 */
class RunnerController extends Controller
{
    private $runnerService;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->runnerService = new RunnerService();
    }

    public function actionRunQueue()
    {
        $this->runnerService->runActualQueue();
    }
}
