<?php

namespace app\modules\apiTesting\commands;

use app\modules\apiTesting\services\RunnerScheduleManager;
use yii\console\Controller;

/**
 * Class ScheduleController
 * @property RunnerScheduleManager $scheduleManager
 */
class ScheduleController extends Controller
{
    private $scheduleManager;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->scheduleManager = new RunnerScheduleManager();
    }

    public function actionUpdateRunnerBySchedule()
    {
        $this->scheduleManager->addScheduledJobsToRunner();
    }
}
