<?php

namespace app\modules\apiTesting\commands;

use app\modules\apiTesting\models\ApiTestServer;
use app\modules\apiTesting\services\ServerService;
use yii\console\Controller;

/**
 * Class ServerController
 *
 * @package app\modules\apiTesting\commands
 *
 * @property ServerService $serverService
 */
class ServerController extends Controller
{
    private $serverService;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->serverService = new ServerService();
    }

    /**
     * Помечает серверы как верефицированые если у них есть соответствующая ДНС запись
     */
    public function actionVerifyServers()
    {
        foreach (ApiTestServer::find()->unverified()->all() as $server) {
            $this->serverService->checkTxtOnServerAndVerify($server);
        }
    }
}
